### ISSUE TITLE
Bug: api methods doesn't generate properly

### ISSUE THREAD

**Issue by LazarenkoA** [xelaj/mtproto#5]
* ОС windows 10
* go version go1.14 windows/amd64

взял пример https://github.com/xelaj/mtproto/tree/master/examples/auth (добавил go.mod)
выполнил  `go get github.com/xelaj/mtproto`, при выполнении `go generate github.com/xelaj/mtproto`  выводится сообщение 
> go: not generating in packages in dependency modules

при сборки тестового примера получаю такое сообщение
```
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\common.go:71:19: undefined: InputClientProxy
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\common.go:72:18: undefined: JSONValue
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\decoder_constructors.go:16:11: undefined: InputGameShortName
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\decoder_constructors.go:18:11: undefined: PageListOrderedItemText
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\decoder_constructors.go:20:11: undefined: UpdateBotInlineSend
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\decoder_constructors.go:22:11: undefined: SecureValueErrorFile
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\functions.go:26:15: undefined: CodeSettings
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\functions.go:43:88: undefined: CodeSettings
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\functions.go:43:104: undefined: AuthSentCode
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\functions.go:82:76: undefined: AuthAuthorization
D:\GoMy\src\pkg\mod\github.com\xelaj\mtproto@v0.0.0-20201004140927-b24d2217ce69\telegram\decoder_constructors.go:22:11: too many errors
```

**Comment by ololosha228** [comment]
Сборка была через `go run ./examples/auth`?

**Comment by patrikhermansson** [comment]
Same issue here but on mac and Go 1.15.

Just cloning the repository and running `go run ./examples/auth ` like you describe gives exactly the same error. Also using `go get github.com/xelaj/mtproto` and auth directly gives the same errors.

`go generate github.com/xelaj/mtproto` doesn't seem to be doing anything. Adding `-x` after gives no commands which it should if it was doing something.

Looking  closer at those files i can't find anywhere where for example the type `CodeSettings` is defined.

**Comment by ololosha228** [comment]
Okay, i found problem: we commited older version of codegen, i'll fix it in [this branch](https://github.com/xelaj/mtproto/tree/rework-codegen) and then merge it into master. Sorry for that.

**Comment by patrikhermansson** [comment]
No problem! I wasn't expecting it to work already to be honest as it was such a new project. But thanks a lot!

**Comment by LazarenkoA** [comment]
> this branch 

чет не работает, такая же проблема

**Comment by ololosha228** [comment]
после фикса и тестов, [этот коммит](https://github.com/xelaj/mtproto/commit/065d8cbf131b5482b80568c574387555a002d887) стал работать. @LazarenkoA @patrikhermansson Есть возможность проверить? У меня работает)

**Comment by patrikhermansson** [comment]
Thanks, it looks better. Still need to try it out, but there is still an issue with this code in `telegram/common.go`:

`func init() {
	keyfile := "~/go/src/github.com/xelaj/mtproto/keys/keys.pem"
	TelegramPublicKeys, err := keys.ReadFromFile(keyfile)
	dry.PanicIfErr(err)
	choosedKey := dry.RandomChoose(dry.InterfaceSlice(TelegramPublicKeys)...).(*rsa.PublicKey)

	_ = choosedKey
}`

It errors because i don't have they key in that location and looking at the code it seems to be a test that doesn't do anything? Haven't made the whole thing work yet but get past this error if i comment this out.

**Comment by ololosha228** [comment]
@patrikhermansson fixed in [this branch](https://github.com/xelaj/mtproto/tree/client_rework) now `telegram.Client` works like... you know, _client_, you just configure it. Hope that this change will resolve your troubles :smile:

**Comment by patrikhermansson** [comment]
Thanks! Think this solves the issue. 

I still can't manage to actually authenticate though, i get an error from `client.AuthSendCode` saying `PHONE_MIGRATE_4 (code 303)`. Judging from this https://core.telegram.org/api/errors it looks like the client works in that it connect correctly but  whatever server ip i try (have used all of the ones in tdlib: https://github.com/tdlib/td/blob/master/td/telegram/net/ConnectionCreator.cpp

But issue remains. Might be that we can close this and open a separate issue for this.

**Comment by LazarenkoA** [comment]
чет у меня не воркает. Делаю `go get -u github.com/xelaj/mtproto@client_rework`
когда процесс доходит до пакета `github.com/xelaj/go-dry` падает
```
# github.com/xelaj/go-dry
D:\GoMy\src\pkg\mod\github.com\xelaj\go-dry@v0.0.0-20201006211243-f7ba64332fc9\path.go:48:9: undefined: unix.Access
D:\GoMy\src\pkg\mod\github.com\xelaj\go-dry@v0.0.0-20201006211243-f7ba64332fc9\path.go:48:34: undefined: unix.W_OK
```
эта же ошибка при сборке тестового примера.

Странно **unix**.Access, я т под виндой работаю

**Comment by LazarenkoA** [comment]
случайно закрыл ишью

**Comment by patrikhermansson** [comment]
> I’m not even cooing. I do `go get -u github.com/xelaj/mtproto@client_rework`
> when the process comes to the package `github.com/xelaj/go-dry`crashes

Yeah that too. I got around it doing a `go get github.com/xelaj/go-dry@latest` and commenting out this:
 if !dry.PathIsWirtable(c.SessionFile) {
   return nil, errs.Permission(c.SessionFile).Scope("write")
}

in `telegram/common.go`

**Comment by patrikhermansson** [comment]
I think one of the issues with the project now is that it doesn't use go modules. If there was a `go.mod` that would ensure that the right versions of all dependencies were fetched. These last issues clearly stem from people having different versions of `go-dry`

**Comment by LazarenkoA** [comment]
@patrikhermansson, спасибо. По клиенту, у меня возвращается 401 и ошибка SESSION_PASSWORD_NEEDED, куда вводить пароль, не понятно, это возвращается после ввода кода который приходит на телефон. 
и кстате в тележку после этого приходит такое сообщение
```
....
Никто не получил доступ к Вашей переписке, потому что входа в аккаунт не произошло. Код был введен верно, но правильный пароль указан не был.
....
```

Может стоит новый ишью завести? (исходная проблема была решена)

**Comment by patrikhermansson** [comment]
@LazarenkoA Agree, the error responses are new issues.

**Comment by LazarenkoA** [comment]
насчет пароля я понял, это из-за включенной у меня двухэтапной аутентификации
